name: skybase
description: Code base for flutter using bloc.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.1.3
  go_router: ^11.1.2
  dio: ^5.2.1+1
  get_it: ^7.6.4
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.3

  # File Manager
  path_provider: ^2.0.15
  image_picker: ^0.8.9
  file_picker: ^5.3.2
  flutter_image_compress: ^2.0.3
  image: 4.0.17
  path: ^1.8.3

  # Widget
  modal_bottom_sheet: ^3.0.0-pre
  infinite_scroll_pagination: ^4.0.0-dev.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7

  # Others
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  url_launcher: ^6.1.11
  permission_handler: ^10.3.0
  intl: ^0.18.0
  open_filex: ^4.3.2
  device_preview: ^1.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
#  change_app_package_name: ^1.1.0
#  rename: ^2.1.1
#  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lib/config/localization/languages/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#
# Usage :
# flutter pub run flutter_launcher_icons
#
#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true
#  remove_alpha_ios: true (Optional)
#  background_color_ios: "#ffffff" (Optional)