name: skybase
description: Code base for flutter using bloc.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  go_router: ^14.4.1
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  sliver_tools: ^0.2.12

  # File Manager
  path_provider: ^2.1.1
  image_picker: ^1.1.2
  file_picker: ^8.1.3
  flutter_image_compress: ^2.3.0
  path: ^1.8.3

  # Widget
  modal_bottom_sheet: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14

  # Others
  collection: ^1.18.0
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  open_filex: ^4.5.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
#  change_app_package_name: ^1.4.0
#  rename: ^3.0.2
#  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lib/core/localization/languages/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300
#
# Usage :
# flutter pub run flutter_launcher_icons
#
#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true
#  remove_alpha_ios: true (Optional)
#  background_color_ios: "#ffffff" (Optional)